export const quickFilters = [
  { label: "همه نوع کالا", category: "all" },
  { label: "موبایل", category: "mobile" },
  { label: "اسباب بازی", category: "toys" },
  { label: "کالای دیجیتال", category: "electronics" },
  { label: "طلا و نقره", category: "jewelry" },
  { label: "مد و پوشاک", category: "fashion" },
  { label: "خانه و آشپزخانه", category: "home_kitchen" },
  { label: "کالای خوراکی و اساسی", category: "grocery" },
  { label: "کتاب، لوازم تحریر و هنر", category: "books_art" },
  { label: "پت شاپ", category: "pet_shop" },
  { label: "لوازم خانگی برقی", category: "home_appliances" },
  { label: "مادر و کودک", category: "mother_child" },
  { label: "سلامت و پزشکی", category: "health_medical" },
  { label: "آرایشی و بهداشتی", category: "beauty_cosmetics" },
  { label: "ورزش و سفر", category: "sports_travel" },
  { label: "ابزار آلات و تجهیزات", category: "tools_equipment" },
  { label: "خودرو و موتورسیکلت", category: "auto_motorcycle" },
  { label: "محصولات بومی و محلی", category: "local_products" },
  { label: "کارت هدیه", category: "gift_card" },
];
export const colors = [
  { name: "مشکی", value: "#000000" },
  { name: "سفید", value: "#ffffff" },
  { name: "قرمز", value: "#ef4444" },
  { name: "آبی", value: "#2563eb" },
  { name: "سبز", value: "#16a34a" },
  { name: "طلایی", value: "#facc15" },
  { name: "صورتی", value: "#ec4899" },
  { name: "نقره‌ای", value: "#9ca3af" },
];
